# Generated by Django 4.2.15 on 2024-09-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatch_player2', to='game_manager.player'),
        ),
    ]
