# Generated by Django 4.2.15 on 2024-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_tournament_is_concluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
