# Generated by Django 4.2.15 on 2024-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_tournament_is_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
