# Generated by Django 4.2.15 on 2024-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_tournament_max_players_tournament_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
