# Generated by Django 4.2.15 on 2024-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0005_tournamentmatch_player1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmatch',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickmatch',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
