# Generated by Django 4.2.15 on 2024-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_quickmatch_player1_score_quickmatch_player2_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
